import { Effect } from "effect";
import { createElement } from "react";
import { renderToStaticMarkup } from "react-dom/server";
import * as loading from "./prevent-dynamic-imports.bad";
import * as staticLoading from "./static-loading.good";
import * as renderBad from "./no-render-side-effects.bad";
import * as renderGood from "./render-action.good";
import * as provideBad from "./no-inline-runtime-provide.bad";
import * as provideGood from "./runtime-boundary.good";
for (const load of [loading.direct, loading.awaited, loading.template, () => loading.variable("./lazy-value")]) if ((await load()).value !== staticLoading.direct()) throw new Error("Module value changed");
if (await staticLoading.task() !== 42) throw new Error("Static task value changed");
const before: string[] = [], after: string[] = [];
for (let i = 0; i < 2; i++) if (renderToStaticMarkup(createElement(renderBad.View, { events: before })) !== renderToStaticMarkup(createElement(renderGood.View))) throw new Error("Render markup changed");
if (before.join() !== "render,render" || after.length !== 0) throw new Error("Bad render evidence changed");
const action = renderGood.action(after);
if (after.length !== 0 || await Effect.runPromise(action) !== 42 || after.join() !== "action") throw new Error("Owned action execution changed");
for (const value of [renderBad.pure(), renderBad.unused(), renderGood.free(), renderGood.alias(), renderGood.computed()]) if (value !== 42) throw new Error("Statement control changed");
for (const task of [provideBad.member, provideBad.free, provideBad.inline, provideBad.multiple, provideBad.empty, provideGood.boundary, provideGood.opaque, provideGood.alias]) if (await Effect.runPromise(task) !== 42) throw new Error("Provision output changed");
const original = { _tag: "Q50Failure" };
const failed = Effect.provide(Effect.fail(original), (await import("./runtime-service")).live);
if (await Effect.runPromise(Effect.flip(failed)) !== original) throw new Error("Provision failure identity changed");
